### ISSUE TITLE
Will exist a version fff release?

### ISSUE THREAD

**Issue by jetm** [meekrosoft/fff#12]

**Comment by meekrosoft** [comment]
What do you mean by release?  You can find the latest up to date version here:
[https://github.com/meekrosoft/fff/blob/master/fff.h](https://github.com/meekrosoft/fff/blob/master/fff.h)

**Comment by jetm** [comment]
I mean by a release a tarball to download from https://github.com/meekrosoft/fff/releases. But I guess downloading https://github.com/meekrosoft/fff/blob/master/fff.h will be the latest stable version.

**Comment by meekrosoft** [comment]
Yes @jetm that is I think the best approach.  I have set up travis ci builds to automatically run the test suite for every change on master so you can be sure that it is working before you use it.
