### ISSUE TITLE
Parameter for UnityPrintFloat() different between declaration and definition

### ISSUE THREAD

**Issue by dmcminniwc** [meekrosoft/fff#22]
In unity.c `UnityPrintFloat` is defined as `void UnityPrintFloat(UNITY_DOUBLE number)` but it is declared in unity_internals.h as `void UnityPrintFloat(const UNITY_DOUBLE number)`. The parameter is marked as `const` in the header and not in the source which results in a compile time warning from MSVC at least. Please use const in the source as well as the header.

**Comment by usr42** [comment]
Is that issue really referring to fff? Or is that issue meant for [Unity](https://github.com/ThrowTheSwitch/Unity) instead?

**Comment by dmcminniwc** [comment]
Sorry, yes, it's meant to be unity.
