### ISSUE TITLE
Const pointer to const generates a wrong mock

### ISSUE THREAD

**Issue by thomasfinchbr** [meekrosoft/fff#79]
I'm using ceedling and fff framework.

When generating mock for functions like the one below there some errors.
Function to generate mock for:
void test(const void * const test_t);
Generated mock:
DECLARE_FAKE_VALUE_FUNC1(void, const const void*);
It should be:
DECLARE_FAKE_VALUE_FUNC1(void, const void* const);

This error generated warnings like this one, when using IAR compiler Arm 8.32.1:
Warning[Pe083]: type qualifier specified more than once 

Thanks.

**Comment by thomasfinchbr** [comment]
This issue was related do fff plugin for ceedling and to fff itself.

**Comment by meekrosoft** [comment]
Thanks for updating the issue!
