### ISSUE TITLE
EXTERN_C clashes with macro of same name in winnt.h

### ISSUE THREAD

**Issue by CiderMan** [meekrosoft/fff#9]
We have a few files in our unit-tests that need fff.h but also need to include windows.h. Unfortunately, both define a macro EXTERN_C so we get warnings about macro redefinitions:

C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include\winnt.h(359) : warning C4005: 'EXTERN_C' : macro redefinition
        W:\dyn_view\common\interface\unittest/fff.h(86) : see previous definition of 'EXTERN_C'

I suggest that the EXTERN_C/END_EXTERN_C in fff.h be prefixed with FFF_ to avoid this clash. (This is the change we've made locally with search-and-replace and it has resolved the issue.)

Regards,

Steve.

**Comment by meekrosoft** [comment]
This is a great idea!  Could you send me a pull request an I will integrate it in fff

**Comment by CiderMan** [comment]
Thanks Mike. Since this is an issue at work, I'm just confirming that I can assign IP/copyright for this change before I start. (Currently I've only patched fff.h, not the generation script.)
I assume that I just need to update the .rb file, install Ruby and confirm that it produces a usable fff.h?

**Comment by CiderMan** [comment]
You have a pull request!

**Comment by meekrosoft** [comment]
Great, thanks so much!
